/**
 * Generate `docs/conformance-coverage.md` from `docs/conformance-coverage.json` and the
 * corpus indexes. Run `bun run conformance:coverage` after editing either.
 *
 * This is where the conformance case counts live. They used to be repeated as prose in
 * CLAUDE.md, docs/spec/README.md and two ROADMAP boxes, hand-maintained in four places.
 *
 * It renders the manifest; it does NOT verify it. `corpus-parity.test.ts` checks the
 * manifest is complete and CI's `conformance-reconcile.ts` checks it is true. That split is
 * deliberate: this file must be runnable by anyone, with no CI artifacts and no suite run in
 * any language.
 */
import { writeFileSync } from "node:fs";
import { publishedCorpora } from "./conformance-corpora.ts";
import { expectedCases, LANGUAGES, MANIFEST_PATH, readManifest } from "./conformance-manifest.ts";
import { joinRepo } from "./paths.ts";

const OUTPUT_PATH = "docs/conformance-coverage.md";

export function renderCoverage(): string {
  const corpora = publishedCorpora();
  const manifest = readManifest();
  const names = [...corpora.keys()].sort();
  const lines: string[] = [];

  lines.push("<!-- Generated by `bun run conformance:coverage`. Do not edit by hand. -->");
  lines.push("");
  lines.push("# Conformance coverage");
  lines.push("");
  lines.push(
    "Which published conformance corpus each SDK binding executes, and how many cases that is.",
  );
  lines.push("");
  lines.push(
    `Generated from [\`${MANIFEST_PATH}\`](./conformance-coverage.json) and the corpus indexes`,
  );
  lines.push(
    "under `docs/spec/conformance/v1/`. The declaration is held **complete** by",
    "`sdks/typescript/scripts/corpus-parity.test.ts` and held **true**, case for case, by CI's",
    "`conformance-report` job — which runs every binding's corpus suite with",
    "`NIMBUS_CONFORMANCE_REPORT` set and reconciles what each one actually executed.",
  );
  lines.push("");

  // The matrix.
  lines.push(`| Corpus | Cases | ${LANGUAGES.join(" | ")} |`);
  lines.push(`|---|---:|${LANGUAGES.map(() => "---").join("|")}|`);
  const totals = new Map(LANGUAGES.map((language) => [language, 0]));
  let grandTotal = 0;
  for (const name of names) {
    const count = (corpora.get(name) ?? []).length;
    grandTotal += count;
    const cells = LANGUAGES.map((language) => {
      if (!manifest.languages[language].claims.includes(name)) return "—";
      // Derived from expectedCases rather than from `deferred.length`, so this page and the
      // reconciler cannot disagree. They did: expectedCases subtracts by SET membership, so a
      // duplicated or unknown deferred entry removed fewer cases there than a raw array
      // length removed here — the rendered total would drop while the expected set did not.
      // `corpus-parity.test.ts` rejects both malformed shapes; this makes the arithmetic
      // agree by construction even so.
      const expected = expectedCases(language, name).length;
      const deferred = count - expected;
      totals.set(language, (totals.get(language) ?? 0) + expected);
      return deferred === 0 ? `${count}` : `${expected} of ${count}`;
    });
    lines.push(`| \`${name}\` | ${count} | ${cells.join(" | ")} |`);
  }
  lines.push(
    `| **Total** | **${grandTotal}** | ${LANGUAGES.map((l) => `**${totals.get(l)}**`).join(" | ")} |`,
  );
  lines.push("");

  // Why a binding skips a corpus.
  lines.push("## What each binding does not run, and why");
  lines.push("");
  for (const language of LANGUAGES) {
    const { unclaimed } = manifest.languages[language];
    const entries = Object.entries(unclaimed).sort(([a], [b]) => a.localeCompare(b));
    lines.push(`### \`${language}\``);
    lines.push("");
    if (entries.length === 0) {
      lines.push("Runs every published corpus.");
    } else {
      for (const [corpus, reason] of entries) lines.push(`- \`${corpus}\` — ${reason}`);
    }
    lines.push("");
  }

  // Deferrals.
  const deferrals = LANGUAGES.flatMap((language) =>
    Object.entries(manifest.languages[language].deferred).flatMap(([corpus, files]) =>
      files.map((file) => `- \`${language}\` defers \`${corpus}\` case \`${file}\``),
    ),
  );
  lines.push("## Deferred cases");
  lines.push("");
  lines.push(
    deferrals.length === 0
      ? "None. Every binding runs every case of every corpus it claims."
      : deferrals.join("\n"),
  );
  lines.push("");

  // The local-use note the review asked for.
  lines.push("## Running the reports locally");
  lines.push("");
  lines.push(
    "Each binding records what it executed only when `NIMBUS_CONFORMANCE_REPORT` names a",
    "directory; unset, recording is a no-op and every suite behaves exactly as it does today.",
    "",
    "**It is for full-suite runs only.** Setting it and then filtering — `pytest -k negotiation`,",
    "`go test -run TestFramingCorpus/single_frame`, `bun test scripts/framing-guard.test.ts` —",
    "produces a truthful but partial report, and reconciling that fails: nothing can tell a",
    "filtered run from a broken one. The reconciler runs in CI, where nothing filters, and is",
    "part of no local test command.",
    "",
    "**Go needs `-count=1`.** A second identical `go test ./conformance/` is served from the",
    "test cache, prints `ok (cached)`, and writes no report files at all — so reconciling picks",
    "up whatever the previous run left behind, or nothing. The CI step passes `-count=1` for",
    "the same reason.",
  );
  lines.push("");

  return `${lines.join("\n")}\n`;
}

if (import.meta.main) {
  writeFileSync(joinRepo(OUTPUT_PATH), renderCoverage(), "utf8");
  // process.stdout.write, not console.log: biome's noConsole is an error outside *.test.ts.
  process.stdout.write(`wrote ${OUTPUT_PATH}\n`);
}
