"""Drive the pure envelope layer from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases.

**This binding claims the corpus and executes two of its five kinds.** ``base64url``
(§4) and ``thumbprint`` (§5) run here; ``ed25519`` (§7's primitive), ``verify`` (§8) and
``sign`` (§9) are deferred, because all three need Ed25519 and CPython ships no stdlib
primitive for it — see ``nimbus_sdk.signing``'s own docstring. §9's last paragraph
admits the primitives layer as conformant on its own, so this is a partial claim the
document allows rather than a gap.

A partial claim is only honest if the two halves cannot drift, which is what
:func:`test_skipped_cases_are_exactly_the_declared_deferrals` is for.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from _conformance_report import corpus_files, recorder

from nimbus_sdk import load_corpus
from nimbus_sdk.signing import (
    SignatureError,
    base64url_decode,
    base64url_encode,
    canonicalize,
    jwk_thumbprint,
)

CASES = load_corpus("manifest-signature")
FILES = corpus_files("manifest-signature")
assert len(FILES) == len(CASES), "the index and load_corpus disagree on the case count"
_RECORDER = recorder("manifest-signature")

#: ``docs/conformance-coverage.json``, from ``sdks/python/tests/`` — three parents up.
#: Not in ``spec_root()``: the declaration is a repository fact about every binding, not
#: part of the language-neutral spec tree, so it is neither bundled into the wheel nor
#: readable from an installed copy.
_COVERAGE = Path(__file__).resolve().parents[3] / "docs" / "conformance-coverage.json"

# Filter the (file, case) PAIRS together — filtering CASES and then zipping FILES back
# in would misalign every case after the first one a kind excludes.
PAIRS = list(zip(FILES, CASES, strict=True))

#: The two kinds this binding executes, and the three it defers. Both sets are named:
#: a kind in neither fails `test_every_corpus_kind_is_accounted_for` rather than going
#: silently unexecuted.
IMPLEMENTED_KINDS = {"base64url", "thumbprint"}
DEFERRED_KINDS = {"ed25519", "verify", "sign"}

BASE64URL_PAIRS = [(f, c) for f, c in PAIRS if c["kind"] == "base64url"]
THUMBPRINT_PAIRS = [(f, c) for f, c in PAIRS if c["kind"] == "thumbprint"]


def executed_case_files() -> set[str]:
    """The ``file`` identity of every case this module runs.

    Derived from the kinds rather than listed, so a new case of an implemented kind is
    executed and a new case of a deferred kind is declared — never the other way round.
    """
    return {f for f, c in PAIRS if c["kind"] in IMPLEMENTED_KINDS}


def _ids(value: object) -> str:
    return str(value["description"])[:70] if isinstance(value, dict) else str(value)


def _reason(case: dict[str, object]) -> str | None:
    """The case's expected §10 token, or ``None`` when it expects success."""
    expect = case["expect"]
    assert isinstance(expect, dict)
    assert ("ok" in expect) != ("rejected" in expect), (
        "expect must carry exactly one of ok and rejected"
    )
    rejected = expect.get("rejected")
    return None if rejected is None else str(rejected)


def _ok(case: dict[str, object]) -> object:
    expect = case["expect"]
    assert isinstance(expect, dict)
    return expect["ok"]


# --------------------------------------------------------------- structural guards


def test_every_corpus_kind_is_accounted_for() -> None:
    # A sixth kind appearing in the corpus fails here rather than being silently
    # neither executed nor deferred.
    assert {case["kind"] for case in CASES} == IMPLEMENTED_KINDS | DEFERRED_KINDS


def test_the_corpus_is_substantial() -> None:
    # A floor, not an exact pin: both other bindings read the same index.json, so a
    # duplicated exact count would detect nothing while making every new case a
    # multi-file edit. It matches the floor the TypeScript and Go guards carry.
    assert len(CASES) >= 40


def test_neither_implemented_kind_is_vacuous() -> None:
    # The failure this catches is a misspelled kind filter, which would leave a
    # parametrised test with zero cases — collected as nothing at all, and green.
    assert len(BASE64URL_PAIRS) > 0
    assert len(THUMBPRINT_PAIRS) > 0
    assert len(executed_case_files()) == len(BASE64URL_PAIRS) + len(THUMBPRINT_PAIRS)


def test_both_outcomes_are_exercised_in_each_implemented_kind() -> None:
    # A kind whose cases all expect success would pin no rejection token at all.
    for pairs in (BASE64URL_PAIRS, THUMBPRINT_PAIRS):
        assert {_reason(c) is None for _, c in pairs} == {True, False}


def test_skipped_cases_are_exactly_the_declared_deferrals() -> None:
    """The runner and ``conformance-coverage.json`` must not disagree.

    Without this, adding a case is silent in BOTH directions: the runner would not run
    it and the reconciler would not expect it, and the corpus would report a coverage it
    does not have. The declaration is read rather than restated here — a hard-coded list
    would make this test agree with itself and nothing else.
    """
    manifest = json.loads(_COVERAGE.read_text(encoding="utf-8"))
    declared = set(manifest["languages"]["python"]["deferred"]["manifest-signature"])
    # `FILES` is the index's own `file` list — `load_corpus` returns case BODIES and
    # discards that member, so the identities come from `corpus_files` rather than from
    # a second source of truth for the same list.
    assert set(FILES) - executed_case_files() == declared


# ------------------------------------------------------------------------------ §4


@pytest.mark.parametrize(("file", "case"), BASE64URL_PAIRS, ids=_ids)
def test_base64url_cases(file: str, case: dict[str, object]) -> None:
    mode = case["mode"]
    text = str(case["input"])
    reason = _reason(case)

    if mode == "encode":
        assert reason is None, "an encoder cannot refuse, yet the case expects a token"
        assert base64url_encode(bytes.fromhex(text)) == _ok(case)
        _RECORDER.record(file)
        return

    if reason is not None:
        with pytest.raises(SignatureError) as excinfo:
            base64url_decode(text)
        assert excinfo.value.reason == reason
    else:
        assert base64url_decode(text).hex() == _ok(case)
    _RECORDER.record(file)


# ------------------------------------------------------------------------------ §5


@pytest.mark.parametrize(("file", "case"), THUMBPRINT_PAIRS, ids=_ids)
def test_thumbprint_cases(file: str, case: dict[str, object]) -> None:
    key = case["jwk"]
    reason = _reason(case)

    if reason is not None:
        with pytest.raises(SignatureError) as excinfo:
            jwk_thumbprint(key)  # type: ignore[arg-type]
        assert excinfo.value.reason == reason
        _RECORDER.record(file)
        return

    assert jwk_thumbprint(key) == _ok(case)  # type: ignore[arg-type]

    # Where the case pins §5 step 2's octets, assert them too: a binding can reach the
    # right digest by the wrong serialization only if the hash input is never asserted.
    expect = case["expect"]
    assert isinstance(expect, dict)
    canonical = expect.get("canonical")
    if canonical is not None:
        assert isinstance(key, dict)
        projection = {member: key[member] for member in ("crv", "kty", "x")}
        assert canonicalize(projection).encode("utf-8").hex() == canonical
    _RECORDER.record(file)
