"""Drive the diagnostics envelope from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases.

**Generated-content expansion.** ``case.schema.json``'s ``#/definitions/textLike``
lets a case describe a large string as ``{"repeat": {"utf8": ..., "count": ...}}`` or
``{"concat": [...]}`` instead of inlining it, so a case at the ``IPC_MAX_LINE_BYTES``
limit (``line-too-long-rejected.json``, ``line-at-limit-accepted.json``) costs a few
lines instead of a megabyte of literal characters. ``load_corpus`` returns cases
exactly as they sit on disk — descriptors included — so this module resolves them
before executing anything, mirroring
``sdks/typescript/scripts/diagnostics-guard.test.ts``'s ``expandEvent`` /
``resolveTextLike`` exactly: a descriptor is recognised and resolved anywhere inside
an encode case's ``event`` (recursively, through arrays and nested objects, not just
at ``extensionId``), and separately inside ``expect.line`` when that is itself a
descriptor rather than a plain string. Parse cases are left untouched — the schema
types ``line`` as a plain string with no textLike variant, and the TypeScript guard
does not expand parse cases either.
"""

from __future__ import annotations

import pytest

from nimbus_sdk import load_corpus
from nimbus_sdk.diagnostics import (
    EncodeOk,
    EncodeRejected,
    ParseOk,
    ParseRejected,
    encode_diagnostic,
    meets_level,
    parse_diagnostic,
)


def _is_repeat_node(value: object) -> bool:
    if not isinstance(value, dict):
        return False
    repeat = value.get("repeat")
    if not isinstance(repeat, dict):
        return False
    return isinstance(repeat.get("utf8"), str) and isinstance(repeat.get("count"), int)


def _is_concat_node(value: object) -> bool:
    return isinstance(value, dict) and isinstance(value.get("concat"), list)


def _resolve_text_like(value: object) -> str:
    """A textLike value (string | repeat | concat of textLike) resolved to a string."""
    if isinstance(value, str):
        return value
    if _is_repeat_node(value):
        assert isinstance(value, dict)
        repeat = value["repeat"]
        assert isinstance(repeat, dict)
        utf8 = repeat["utf8"]
        count = repeat["count"]
        assert isinstance(utf8, str)
        assert isinstance(count, int)
        return utf8 * count
    if _is_concat_node(value):
        assert isinstance(value, dict)
        parts = value["concat"]
        assert isinstance(parts, list)
        return "".join(_resolve_text_like(part) for part in parts)
    raise ValueError(f"not text-like: {value!r}")


def _expand_event(value: object) -> object:
    """Recursively resolve any repeat/concat descriptor inside an encode case's
    event."""
    if _is_repeat_node(value) or _is_concat_node(value):
        return _resolve_text_like(value)
    if isinstance(value, list):
        return [_expand_event(item) for item in value]
    if isinstance(value, dict):
        return {key: _expand_event(item) for key, item in value.items()}
    return value


def _expand_case(case: dict[str, object]) -> dict[str, object]:
    if case.get("kind") != "encode":
        return case
    expanded: dict[str, object] = dict(case)
    expanded["event"] = _expand_event(case["event"])
    expect = case.get("expect")
    has_line = isinstance(expect, dict) and "line" in expect
    line_is_descriptor = has_line and not isinstance(expect["line"], str)  # type: ignore[index]
    if line_is_descriptor:
        assert isinstance(expect, dict)
        expect = dict(expect)
        expect["line"] = _resolve_text_like(expect["line"])
        expanded["expect"] = expect
    return expanded


CASES = [_expand_case(case) for case in load_corpus("diagnostics")]

IMPLEMENTED_KINDS = {"encode", "parse", "level"}
DEFERRED_KINDS: set[str] = set()


def test_every_corpus_kind_is_accounted_for() -> None:
    assert {case["kind"] for case in CASES} == IMPLEMENTED_KINDS | DEFERRED_KINDS


@pytest.mark.parametrize(
    "case",
    [c for c in CASES if c["kind"] == "encode"],
    ids=lambda c: str(c["description"])[:60],
)
def test_encode_cases(case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    result = encode_diagnostic(case["event"])
    if expect["ok"]:
        assert result == EncodeOk(line=str(expect["line"]))
    else:
        assert result == EncodeRejected(
            reason=str(expect["reason"]), path=str(expect["path"])
        )


@pytest.mark.parametrize(
    "case",
    [c for c in CASES if c["kind"] == "parse"],
    ids=lambda c: str(c["description"])[:60],
)
def test_parse_cases(case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    result = parse_diagnostic(str(case["line"]))
    if expect["ok"]:
        assert result == ParseOk(event=expect["event"])
    else:
        assert result == ParseRejected(
            reason=str(expect["reason"]), path=str(expect["path"])
        )


@pytest.mark.parametrize(
    "case",
    [c for c in CASES if c["kind"] == "level"],
    ids=lambda c: str(c["description"])[:60],
)
def test_level_cases(case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    assert meets_level(str(case["level"]), str(case["threshold"])) is expect["meets"]
