"""Drive the data-profile battery from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases. ``test_spec_snapshot.py``
catches that; if it is red, this file is testing the wrong bytes.

Cases are discriminated by ``kind`` rather than by an ok/refused outcome, because the
battery is six functions rather than one predicate. So the anti-vacuity assertion here
is that every kind is exercised, where the url-resolution runner asserts both outcomes.

Numbers are compared **numerically, never by type**. Python returns a genuine ``int``
from §5's ``len`` and §7's line count and a genuine ``float`` from §6.1's conversion,
the corpus spells its counts as JSON integers, and ``3 == 3.0`` is ``True``. A runner
asserting ``type(actual) is type(expected)`` would fail every §5 and §7 case for no
reason at all.
"""

from __future__ import annotations

from typing import Any

import pytest
from _conformance_report import corpus_files, recorder

from nimbus_sdk import load_corpus
from nimbus_sdk.data_profile import (
    DataColumn,
    first_line_and_rows,
    js_kind,
    parquet_columns_from_metadata,
    parse_csv_header,
    parse_json_columns,
    parse_jsonl_columns,
)

CASES = load_corpus("data-profile")
FILES = corpus_files("data-profile")
assert len(FILES) == len(CASES), "the index and load_corpus disagree on the case count"
_RECORDER = recorder("data-profile")

#: Every function the battery publishes has a kind, and every kind needs a case.
KINDS = frozenset(
    {
        "js-kind",
        "csv-header",
        "jsonl-columns",
        "json-columns",
        "parquet-columns",
        "first-line-rows",
    }
)


def _ids() -> list[str]:
    return [str(case["description"]) for case in CASES]


def test_the_corpus_is_not_empty() -> None:
    # A load_corpus that silently returned [] would make every parametrised test below
    # vanish rather than fail. A floor, not an exact count: the TypeScript guard is what
    # holds the exact list, and duplicating it here would make every new case a two-file
    # edit while detecting nothing.
    assert len(CASES) >= 30


def test_every_kind_is_exercised() -> None:
    # The counterpart of the url-resolution runner's both-outcomes assertion. A corpus
    # that silently lost a kind would leave a whole function untested while passing.
    assert {str(case["kind"]) for case in CASES} == KINDS


def _columns(raw: object) -> list[dict[str, object]]:
    """The expected columns, as plain dicts."""
    assert isinstance(raw, list)
    return [dict(entry) for entry in raw]


def _as_dicts(columns: list[DataColumn]) -> list[dict[str, object]]:
    """Convert the binding's output for comparison, never the case data.

    Adapting the case instead would let a case with a mistyped key match silently.
    """
    return [{"name": column.name, "type": column.type} for column in columns]


def _run(case: dict[str, Any]) -> dict[str, Any]:
    kind = case["kind"]
    if kind == "js-kind":
        return {"kind": js_kind(case["value"])}
    if kind == "csv-header":
        return {"columns": _as_dicts(parse_csv_header(str(case["line"])))}
    if kind == "jsonl-columns":
        return {"columns": _as_dicts(parse_jsonl_columns(str(case["line"])))}
    if kind == "json-columns":
        columns, rows = parse_json_columns(case["value"])
        return {"columns": _as_dicts(columns), "rowCountEstimate": rows}
    if kind == "parquet-columns":
        columns, rows = parquet_columns_from_metadata(case["meta"])
        return {"columns": _as_dicts(columns), "rowCountEstimate": rows}
    if kind == "first-line-rows":
        first_line, rows = first_line_and_rows(
            str(case["text"]), bool(case["truncated"])
        )
        return {"firstLine": first_line, "rowCountEstimate": rows}
    raise AssertionError(f"unknown kind {kind!r}")


@pytest.mark.parametrize(
    ("file", "case"), list(zip(FILES, CASES, strict=True)), ids=_ids()
)
def test_case(file: str, case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    actual = _run(dict(case))

    assert set(actual) == set(expect), f"{file}: shape mismatch"
    for key, want in expect.items():
        got = actual[key]
        if key == "columns":
            assert got == _columns(want), f"{file}: {key}"
        else:
            # `==`, not `is` and not a type check: see the module docstring.
            assert got == want, f"{file}: {key}"
    _RECORDER.record(file)
