"""Drive the diagnostics envelope from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases.
"""

from __future__ import annotations

import pytest

from nimbus_sdk import load_corpus
from nimbus_sdk.diagnostics import (
    EncodeOk,
    EncodeRejected,
    ParseOk,
    ParseRejected,
    encode_diagnostic,
    meets_level,
    parse_diagnostic,
)

CASES = load_corpus("diagnostics")

IMPLEMENTED_KINDS = {"encode", "parse", "level"}
DEFERRED_KINDS: set[str] = set()


def test_every_corpus_kind_is_accounted_for() -> None:
    assert {case["kind"] for case in CASES} == IMPLEMENTED_KINDS | DEFERRED_KINDS


def test_the_corpus_is_not_empty() -> None:
    # A misresolved spec_root would yield an empty list and make every parametrized
    # suite below vacuously green.
    assert len(CASES) > 0


@pytest.mark.parametrize(
    "case",
    [c for c in CASES if c["kind"] == "encode"],
    ids=lambda c: str(c["description"])[:60],
)
def test_encode_cases(case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    result = encode_diagnostic(case["event"])
    if expect["ok"]:
        assert result == EncodeOk(line=str(expect["line"]))
    else:
        assert result == EncodeRejected(
            reason=str(expect["reason"]), path=str(expect["path"])
        )


@pytest.mark.parametrize(
    "case",
    [c for c in CASES if c["kind"] == "parse"],
    ids=lambda c: str(c["description"])[:60],
)
def test_parse_cases(case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    result = parse_diagnostic(str(case["line"]))
    if expect["ok"]:
        assert result == ParseOk(event=expect["event"])
    else:
        assert result == ParseRejected(
            reason=str(expect["reason"]), path=str(expect["path"])
        )


@pytest.mark.parametrize(
    "case",
    [c for c in CASES if c["kind"] == "level"],
    ids=lambda c: str(c["description"])[:60],
)
def test_level_cases(case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    assert meets_level(str(case["level"]), str(case["threshold"])) is expect["meets"]
