"""Drive the distribution-channel battery from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases. ``test_spec_snapshot.py``
catches that; if it is red, this file is testing the wrong bytes.

This battery reads the outside world, so every ``resolve`` case supplies all three
injected inputs and this runner never omits one. An absent argument would make
``resolve_distribution_channel`` read ``os.environ`` and ``sys.executable`` and quietly
test THIS MACHINE -- passing or failing by accident, differently on each of the three
operating systems CI runs.

The realpath map's ``None`` means the resolver raises, which is the only way §3.1 is
pinnable: a map alone can express only a resolver that succeeds.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping
from typing import Any

import pytest
from _conformance_report import corpus_files, recorder

from nimbus_sdk import load_corpus
from nimbus_sdk.distribution_channel import (
    channel_upgrade_hint,
    resolve_distribution_channel,
)

CASES = load_corpus("distribution-channel")
FILES = corpus_files("distribution-channel")
assert len(FILES) == len(CASES), "the index and load_corpus disagree on the case count"
_RECORDER = recorder("distribution-channel")

KINDS = frozenset({"resolve", "hint"})


def _ids() -> list[str]:
    return [str(case["description"]) for case in CASES]


def test_the_corpus_is_not_empty() -> None:
    # A load_corpus that silently returned [] would make every parametrised test below
    # vanish rather than fail. A floor, not an exact count: the TypeScript guard holds
    # the exact list, and duplicating it here would detect nothing.
    assert len(CASES) >= 24


def test_every_kind_is_exercised() -> None:
    assert {str(case["kind"]) for case in CASES} == KINDS


def test_a_resolver_that_raises_is_pinned() -> None:
    # §3.1 is the reason the realpath map allows None at all. Without a case using it,
    # the whole failing-resolver rule is untested in this binding too.
    raising = []
    for case in CASES:
        if case["kind"] != "resolve":
            continue
        realpath = case["realpath"]
        assert isinstance(realpath, dict)
        if None in realpath.values():
            raising.append(case)
    assert len(raising) >= 2, "no case pins a resolver that fails"


def _realpath_from(mapping: Mapping[str, str | None]) -> Callable[[str], str]:
    """The case's realpath map as an injectable resolver.

    A path absent from the map resolves to itself; a path mapping to ``None`` raises,
    which is what a real resolver does for a path it cannot resolve.
    """

    def resolve(path: str) -> str:
        if path not in mapping:
            return path
        target = mapping[path]
        if target is None:
            raise OSError(f"ENOENT: cannot resolve {path}")
        return target

    return resolve


@pytest.mark.parametrize(
    ("file", "case"), list(zip(FILES, CASES, strict=True)), ids=_ids()
)
def test_case(file: str, case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    kind = case["kind"]

    if kind == "hint":
        channel = case["channel"]
        assert isinstance(channel, str)
        assert channel_upgrade_hint(channel) == expect["text"]  # type: ignore[arg-type]
        _RECORDER.record(file)
        return

    # Checked rather than defaulted: an absent input would silently read this machine.
    env: Any = case["env"]
    exec_path: Any = case["execPath"]
    realpath: Any = case["realpath"]
    assert isinstance(env, dict), f"{file}: no env"
    assert isinstance(exec_path, str), f"{file}: no execPath"
    assert isinstance(realpath, dict), f"{file}: no realpath"

    actual = resolve_distribution_channel(
        env=env, exec_path=exec_path, realpath=_realpath_from(realpath)
    )
    assert actual == expect["channel"], f"{file}"
    _RECORDER.record(file)
