"""Drive the negotiation algorithm from the published conformance corpus.

This is the first proof that two languages speak one contract: the TypeScript guard
and this test read the identical case files.
"""

from __future__ import annotations

from collections.abc import Sequence

import pytest

from nimbus_sdk import (
    CONTRACT_HANDSHAKE_EXIT,
    NegotiationOk,
    NegotiationRefused,
    NegotiationResult,
    declared_versions_match,
    load_corpus,
    manifest_contract_versions,
    negotiate_contract_version,
)

# Reads the spec data bundled at build time into `src/nimbus_sdk/_data/spec`, which
# `spec_root()` prefers over the repository's `docs/spec`. That copy is gitignored and
# regenerated by the hatch build hook, so **adding a case to `docs/spec` is not enough
# locally**: without `python -m pip install -e .` first, this suite runs the previous
# snapshot and passes while executing none of the new cases. CI installs into a clean
# checkout and is unaffected.
CASES = load_corpus("negotiation")

# `hello` cases exercise hello-frame parsing, which lives with the IPC surface this
# package does not yet carry. Skipping them is recorded rather than silent, and the
# test below fails if a *new* kind appears — so the gap cannot widen unnoticed.
IMPLEMENTED_KINDS = {"negotiate", "declaration"}
DEFERRED_KINDS = {"hello"}


def test_every_corpus_kind_is_accounted_for() -> None:
    assert {case["kind"] for case in CASES} == IMPLEMENTED_KINDS | DEFERRED_KINDS


@pytest.mark.parametrize(
    "case",
    [c for c in CASES if c["kind"] == "negotiate"],
    ids=lambda c: str(c["description"])[:60],
)
def test_negotiate_cases(case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    result = negotiate_contract_version(case["local"], case["remote"])  # type: ignore[arg-type]
    if expect["ok"]:
        assert result == NegotiationOk(version=str(expect["version"]))
    else:
        assert result == NegotiationRefused(reason=str(expect["reason"]))


@pytest.mark.parametrize(
    "case",
    [c for c in CASES if c["kind"] == "declaration"],
    ids=lambda c: str(c["description"])[:60],
)
def test_declaration_cases(case: dict[str, object]) -> None:
    # A case's `manifest` field is the RAW declared value of `contractVersions` — a list
    # in the ordinary cases, but deliberately `5` in one of them, and absent entirely in
    # the case that pins the absence default. So it is wrapped into a manifest object
    # here rather than passed straight through; an absent field must stay absent, not
    # become an explicit null, or the absence default would never be exercised.
    manifest: dict[str, object] = {}
    if "manifest" in case:
        manifest = {"contractVersions": case["manifest"]}

    # Two steps, matching the TypeScript binding: extract, then compare.
    declared = manifest_contract_versions(manifest)
    expect = case["expect"]
    assert isinstance(expect, dict)

    matched = declared_versions_match(declared, case["hello"])  # type: ignore[arg-type]
    assert matched is bool(expect["ok"])
    if not expect["ok"]:
        # This layer has exactly one refusal to express; if the corpus ever grows a
        # different reason for a declaration case, this fails rather than passing on a
        # coincidentally-correct boolean.
        assert expect["reason"] == "declaration-mismatch"
        assert expect["exit"] == CONTRACT_HANDSHAKE_EXIT


def _short_circuiting_on_empty(
    local: Sequence[object], remote: Sequence[object]
) -> NegotiationResult:
    """The wrong binding: refuses on an empty set without validating the other side.

    The reading RFC-0006 rejected. Everything else delegates to the real implementation,
    so the test below asserts a property of the *corpus*, not of a private copy of the
    algorithm.
    """
    if not local or not remote:
        return NegotiationRefused(reason="no-common-version")
    return negotiate_contract_version(local, remote)


def test_corpus_refuses_a_binding_that_short_circuits_on_an_empty_set() -> None:
    # Spec section 6 requires validation before intersection, unconditionally. Some
    # case must disagree with the wrapper above; if none does, the corpus admits both
    # readings and a non-conformant binding passes CI.
    caught: list[str] = []
    for case in (c for c in CASES if c["kind"] == "negotiate"):
        expect = case["expect"]
        assert isinstance(expect, dict)
        actual = _short_circuiting_on_empty(case["local"], case["remote"])  # type: ignore[arg-type]
        if expect["ok"]:
            agreed = actual == NegotiationOk(version=str(expect["version"]))
        else:
            agreed = actual == NegotiationRefused(reason=str(expect["reason"]))
        if not agreed:
            caught.append(str(case["description"])[:60])

    assert caught, (
        "no corpus case distinguishes validate-then-intersect from "
        "short-circuit-on-empty — the RFC-0006 empty-vs-invalid cases are missing "
        "or no longer discriminate"
    )
