"""Drive the jmap battery from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases.

Ten kinds, the most of any corpus, because §1's surface is ten operations. One of them
is unlike anything else in the tree: ``validate-url`` cases with ``ok: false`` expect
the function to **raise** (§5.1), not to return an absence, so they use
``pytest.raises`` with an exact message match rather than an equality assertion.

Comparisons convert the BINDING'S output into the corpus's shape rather than the
reverse, so a case with a mistyped key fails rather than silently matching.
"""

from __future__ import annotations

import re
from typing import Any

import pytest
from _conformance_report import corpus_files, recorder

from nimbus_sdk import load_corpus
from nimbus_sdk.jmap_fastmail import (
    CORE_CAPABILITY,
    EMAIL_PROPERTIES,
    MAIL_CAPABILITY,
    MAX_BODY_VALUE_BYTES,
    PREVIEW_MAX_CHARS,
    SUBMISSION_CAPABILITY,
    BuildRequest,
    JmapAttachmentMeta,
    JmapEmailView,
    build_get_request,
    build_list_request,
    build_search_request,
    extract_attachments,
    extract_email_list,
    format_addresses,
    method_response_args,
    parse_session,
    preview_for,
    validate_api_url,
    view_email,
)

CASES = load_corpus("jmap")
FILES = corpus_files("jmap")
assert len(FILES) == len(CASES), "the index and load_corpus disagree on the case count"
_RECORDER = recorder("jmap")

KINDS = frozenset(
    {
        "constants",
        "session",
        "validate-url",
        "view-email",
        "addresses",
        "attachments",
        "preview",
        "request",
        "extract",
        "extract-list",
    }
)

_CONSTANTS: dict[str, object] = {
    "CORE_CAPABILITY": CORE_CAPABILITY,
    "MAIL_CAPABILITY": MAIL_CAPABILITY,
    "SUBMISSION_CAPABILITY": SUBMISSION_CAPABILITY,
    "MAX_BODY_VALUE_BYTES": MAX_BODY_VALUE_BYTES,
    "PREVIEW_MAX_CHARS": PREVIEW_MAX_CHARS,
}


def _expect(case: dict[str, object]) -> dict[str, Any]:
    """The case's ``expect`` as a real mapping.

    load_corpus returns ``dict[str, object]``, so every read off ``expect`` is an
    ``object`` until something narrows it. Narrowing once here beats a ``type: ignore``
    at each use -- mypy rejected three of those as the wrong code or unused, which is
    the suppression telling on itself.
    """
    value = case["expect"]
    assert isinstance(value, dict)
    return value


def _ids() -> list[str]:
    return [str(case["description"]) for case in CASES]


def _attachment(meta: JmapAttachmentMeta) -> dict[str, object]:
    return {
        "name": meta.name,
        "sizeBytes": meta.size_bytes,
        "mimeType": meta.mime_type,
    }


def _view(v: JmapEmailView) -> dict[str, object]:
    """The binding's view in the corpus's shape, all nine members."""
    return {
        "id": v.id,
        "messageId": v.message_id,
        "subject": v.subject,
        "from": list(v.from_),
        "to": list(v.to),
        "cc": list(v.cc),
        "receivedAt": v.received_at,
        "attachments": [_attachment(a) for a in v.attachments],
        "preview": v.preview,
    }


def _request(r: BuildRequest) -> dict[str, object]:
    """The binding's request in the corpus's shape.

    §9: compared as a PARSED STRUCTURE, never as serialised bytes. Go's
    ``encoding/json`` sorts a map's keys on marshal where Python and JavaScript emit
    insertion order, so the same conforming request serialises differently in different
    bindings.
    """
    return {
        "using": list(r.using),
        "methodCalls": [
            [name, args, client_id] for name, args, client_id in r.method_calls
        ],
    }


def test_the_corpus_is_not_empty() -> None:
    # A load_corpus that silently returned [] would make every parametrised test below
    # vanish rather than fail. A floor, not an exact count: the TypeScript guard holds
    # the exact list, and duplicating it here would detect nothing.
    assert len(CASES) >= 55


def test_every_kind_is_exercised() -> None:
    assert {str(case["kind"]) for case in CASES} == KINDS


def test_both_validate_url_outcomes_are_exercised() -> None:
    # §5.1 makes this the one function in any battery that RAISES. Without a case for
    # each outcome, either the acceptance path or the whole raising rule goes untested.
    outcomes = {
        bool(_expect(case)["ok"]) for case in CASES if case["kind"] == "validate-url"
    }
    assert outcomes == {True, False}


def test_the_three_host_hazards_are_pinned() -> None:
    # Measured: the three URL parsers disagree three ways and a DIFFERENT pair agrees
    # each time. Python's own hazard is the default port and the IPv6 brackets, so these
    # cases are the ones that would catch a naive _host_key here.
    candidates = [
        str(case["candidate"]) for case in CASES if case["kind"] == "validate-url"
    ]
    assert any(":443/" in c for c in candidates), (
        "no case pins an explicit default port"
    )
    assert any("[" in c for c in candidates), "no case pins an IPv6 literal"
    assert any(re.search(r"[A-Z]", c.split("//", 1)[-1]) for c in candidates), (
        "no case pins a mixed-case host"
    )


def test_no_expected_preview_is_ill_formed() -> None:
    # A lone surrogate cannot be encoded as UTF-8, so a corpus expecting one would pin a
    # value this binding raises on when the caller serialises it.
    for case in CASES:
        preview = _expect(case).get("preview")
        if isinstance(preview, str):
            preview.encode("utf-8")  # raises UnicodeEncodeError on a lone surrogate


@pytest.mark.parametrize(
    ("file", "case"), list(zip(FILES, CASES, strict=True)), ids=_ids()
)
def test_case(file: str, case: dict[str, object]) -> None:
    expect = _expect(case)
    kind = case["kind"]

    if kind == "constants":
        constants = expect.get("constants")
        if constants is not None:
            for name, want in constants.items():
                assert _CONSTANTS[name] == want, f"{file}: {name}"
        properties = expect.get("emailProperties")
        if properties is not None:
            assert list(EMAIL_PROPERTIES) == properties, file
        _RECORDER.record(file)
        return

    if kind == "session":
        session = parse_session(case["parsed"])
        actual = (
            None
            if session is None
            else {"apiUrl": session.api_url, "accountId": session.account_id}
        )
        assert actual == expect["session"], file
        _RECORDER.record(file)
        return

    if kind == "validate-url":
        candidate: Any = case["candidate"]
        allowed_base: Any = case["allowedBase"]
        assert isinstance(candidate, str), f"{file}: no candidate"
        assert isinstance(allowed_base, str), f"{file}: no allowedBase"
        if expect["ok"]:
            assert validate_api_url(candidate, allowed_base) == expect["url"], file
            _RECORDER.record(file)
            return
        # §5.1 -- it RAISES. The message is contract text (§R5), so the match is exact
        # rather than a substring: re.escape, anchored at both ends.
        with pytest.raises(ValueError, match=f"^{re.escape(str(expect['message']))}$"):
            validate_api_url(candidate, allowed_base)
        _RECORDER.record(file)
        return

    if kind == "view-email":
        result = view_email(case["raw"])
        assert (None if result is None else _view(result)) == expect["view"], file
        _RECORDER.record(file)
        return

    if kind == "addresses":
        assert list(format_addresses(case["value"])) == expect["formatted"], file
        _RECORDER.record(file)
        return

    if kind == "attachments":
        actual_atts = [_attachment(a) for a in extract_attachments(case["value"])]
        assert actual_atts == expect["attachments"], file
        _RECORDER.record(file)
        return

    if kind == "preview":
        raw: Any = case["raw"]
        assert isinstance(raw, dict), f"{file}: no raw record"
        assert preview_for(raw) == expect["preview"], file
        _RECORDER.record(file)
        return

    if kind == "request":
        account_id: Any = case["accountId"]
        assert isinstance(account_id, str), f"{file}: no accountId"
        form = case["form"]
        limit: Any = case.get("limit")
        if form == "list":
            assert isinstance(limit, int), f"{file}: no limit"
            built = build_list_request(account_id, limit)
        elif form == "search":
            assert isinstance(limit, int), f"{file}: no limit"
            built = build_search_request(account_id, str(case["query"]), limit)
        else:
            built = build_get_request(account_id, str(case["id"]))
        assert _request(built) == expect["request"], file
        _RECORDER.record(file)
        return

    if kind == "extract":
        method_name: Any = case["methodName"]
        assert isinstance(method_name, str), f"{file}: no methodName"
        assert method_response_args(case["parsed"], method_name) == expect["args"], file
        _RECORDER.record(file)
        return

    assert kind == "extract-list", f"{file}: unknown kind {kind!r}"
    assert extract_email_list(case["parsed"]) == expect["list"], file
    _RECORDER.record(file)
