"""Drive ``resolve_url_with_base`` from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases.

The cases carry the exact §7 message, not only the verdict, so the two bindings are held
to the same words. That is the whole reason the message is in the case file rather than
in each binding's own unit tests.
"""

from __future__ import annotations

import pytest
from _conformance_report import corpus_files, recorder

from nimbus_sdk import load_corpus
from nimbus_sdk.connector_kit import UrlResolutionError, resolve_url_with_base

CASES = load_corpus("url-resolution")
FILES = corpus_files("url-resolution")
assert len(FILES) == len(CASES), "the index and load_corpus disagree on the case count"
_RECORDER = recorder("url-resolution")


def _ids() -> list[str]:
    return [str(case["description"]) for case in CASES]


def test_the_corpus_is_not_empty() -> None:
    # A load_corpus that silently returned [] would make every parametrised test below
    # vanish rather than fail. Twenty-five is the count at the corpus's introduction;
    # the TypeScript guard is what holds the exact list.
    assert len(CASES) >= 25


def _outcome(case: dict[str, object]) -> bool:
    expect = case["expect"]
    assert isinstance(expect, dict)
    return bool(expect["ok"])


def test_both_outcomes_are_exercised() -> None:
    # A corpus of only-accepts or only-refuses is not coverage. The TypeScript guard
    # makes the same assertion; both bindings refuse to report a half-corpus as passing.
    assert {_outcome(case) for case in CASES} == {True, False}


@pytest.mark.parametrize(
    ("file", "case"), list(zip(FILES, CASES, strict=True)), ids=_ids()
)
def test_case(file: str, case: dict[str, object]) -> None:
    base = case["base"]
    input_ = case["input"]
    expect = case["expect"]
    assert isinstance(base, str)
    assert isinstance(input_, str)
    assert isinstance(expect, dict)

    if expect["ok"]:
        assert resolve_url_with_base(base, input_) == expect["url"]
        _RECORDER.record(file)
        return

    with pytest.raises(UrlResolutionError) as excinfo:
        resolve_url_with_base(base, input_)
    assert str(excinfo.value) == expect["message"]
    _RECORDER.record(file)
