"""Drive the whole manifest-signature layer from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases.

**This binding claims the corpus and executes all five of its kinds.** ``base64url``
(§4), ``thumbprint`` (§5), ``ed25519`` (§7's primitive), ``verify`` (§8) and ``sign``
(§9). Nothing is deferred: the private RFC 8032 implementation in
``nimbus_sdk.signing._ed25519`` is what removed the reason there ever was one — CPython
ships no stdlib Ed25519, and this package's ``[project].dependencies`` stays empty.

The ``verify`` runner is the load-bearing one. §8's step order is normative, and every
ordering verifies exactly the same set of *valid* signatures — the orders differ only in
which §10 token an *invalid* manifest reports. So the four ordering resolutions §8
spells out (an unknown ``kid`` beats a bogus ``alg``; a bogus ``alg`` beats an
uncanonicalizable manifest; both envelope members decode before either is parsed;
``protected-malformed`` beats ``crit-unsupported``) are pinned by nothing at all unless
these cases execute. That is what
:func:`test_every_case_is_parametrised_into_exactly_one_runner` exists to keep true.

A claim is only honest if the runner and the declaration cannot drift, which is what
:func:`test_skipped_cases_are_exactly_the_declared_deferrals` is for — and it is *more*
valuable now that the expected answer is the empty set, because "skipped nothing"
silently stops being true the first time someone adds a ``pytest.mark.skip``.
"""

from __future__ import annotations

import json
from itertools import chain
from pathlib import Path

import pytest
from _conformance_report import corpus_files, recorder

from nimbus_sdk import load_corpus

# `_ed25519` is deliberately NOT part of `nimbus_sdk.signing`'s surface — see that
# package's docstring — so the §7 kind reaches the private module by name. It is the one
# private import in this suite, and it is what makes §7 executable at all.
from nimbus_sdk.signing import (
    SIGNATURE_REASONS,
    SignatureError,
    _ed25519,
    base64url_decode,
    base64url_encode,
    canonicalize,
    jwk_thumbprint,
    sign_manifest,
    verify_manifest_signature,
)

CASES = load_corpus("manifest-signature")
FILES = corpus_files("manifest-signature")
assert len(FILES) == len(CASES), "the index and load_corpus disagree on the case count"
_RECORDER = recorder("manifest-signature")

#: ``docs/conformance-coverage.json``, from ``sdks/python/tests/`` — three parents up.
#: Not in ``spec_root()``: the declaration is a repository fact about every binding, not
#: part of the language-neutral spec tree, so it is neither bundled into the wheel nor
#: readable from an installed copy.
_COVERAGE = Path(__file__).resolve().parents[3] / "docs" / "conformance-coverage.json"

# Filter the (file, case) PAIRS together — filtering CASES and then zipping FILES back
# in would misalign every case after the first one a kind excludes.
PAIRS = list(zip(FILES, CASES, strict=True))

#: The five kinds this binding executes, and the none it defers. Both sets are still
#: named: a kind in neither fails `test_every_corpus_kind_is_accounted_for` rather than
#: going silently unexecuted, and an empty `DEFERRED_KINDS` is a statement rather than
#: an absence.
IMPLEMENTED_KINDS = {"base64url", "thumbprint", "ed25519", "verify", "sign"}
DEFERRED_KINDS: set[str] = set()

BASE64URL_PAIRS = [(f, c) for f, c in PAIRS if c["kind"] == "base64url"]
THUMBPRINT_PAIRS = [(f, c) for f, c in PAIRS if c["kind"] == "thumbprint"]
ED25519_PAIRS = [(f, c) for f, c in PAIRS if c["kind"] == "ed25519"]
VERIFY_PAIRS = [(f, c) for f, c in PAIRS if c["kind"] == "verify"]
SIGN_PAIRS = [(f, c) for f, c in PAIRS if c["kind"] == "sign"]

#: Every kind list, in the order the sections run. One place to add a sixth, so a new
#: kind cannot be routed by one guard and missed by another.
ALL_KIND_PAIRS = (
    BASE64URL_PAIRS,
    THUMBPRINT_PAIRS,
    ED25519_PAIRS,
    VERIFY_PAIRS,
    SIGN_PAIRS,
)


def executed_case_files() -> set[str]:
    """The ``file`` identity of every case this module runs.

    Derived from the kinds rather than listed, so a new case of an implemented kind is
    executed and a new case of a deferred kind is declared — never the other way round.
    """
    return {f for f, c in PAIRS if c["kind"] in IMPLEMENTED_KINDS}


def _ids(value: object) -> str:
    return str(value["description"])[:70] if isinstance(value, dict) else str(value)


def _reason(case: dict[str, object]) -> str | None:
    """The case's expected §10 token, or ``None`` when it expects success."""
    expect = case["expect"]
    assert isinstance(expect, dict)
    assert ("ok" in expect) != ("rejected" in expect), (
        "expect must carry exactly one of ok and rejected"
    )
    rejected = expect.get("rejected")
    return None if rejected is None else str(rejected)


def _ok(case: dict[str, object]) -> object:
    expect = case["expect"]
    assert isinstance(expect, dict)
    return expect["ok"]


def _canonicalization_reason(case: dict[str, object]) -> str | None:
    """The ``canonical-json.md`` §9 reason a case pins alongside its §10 token.

    §10 requires the underlying reason to be reachable ALONGSIDE
    ``canonicalization-failed`` rather than reported as one of the ten, so it is
    asserted on a field of the exception rather than by parsing its message.
    """
    expect = case["expect"]
    assert isinstance(expect, dict)
    value = expect.get("canonicalizationReason")
    return None if value is None else str(value)


def _outcome(case: dict[str, object]) -> str:
    """A case's outcome identity, for the vacuity guard below.

    Not simply "does it expect a token": the ``ed25519`` kind never REFUSES — §7's
    primitive returns a boolean, so both of its outcomes are ``ok`` and a plain
    success/rejection split would be satisfied by twelve cases that all expect
    ``False``.
    """
    reason = _reason(case)
    if reason is not None:
        return f"rejected:{reason}"
    return f"ok:{_ok(case)!r}" if case["kind"] == "ed25519" else "ok"


# --------------------------------------------------------------- structural guards


def test_every_corpus_kind_is_accounted_for() -> None:
    # A sixth kind appearing in the corpus fails here rather than being silently
    # neither executed nor deferred.
    assert {case["kind"] for case in CASES} == IMPLEMENTED_KINDS | DEFERRED_KINDS


def test_the_corpus_is_substantial() -> None:
    # A floor, not an exact pin: both other bindings read the same index.json, so a
    # duplicated exact count would detect nothing while making every new case a
    # multi-file edit. It matches the floor the TypeScript and Go guards carry.
    assert len(CASES) >= 40


def test_no_implemented_kind_is_vacuous() -> None:
    # The failure this catches is a misspelled kind filter, which would leave a
    # parametrised test with zero cases — collected as nothing at all, and green.
    for pairs in ALL_KIND_PAIRS:
        assert len(pairs) > 0
    assert len(executed_case_files()) == sum(len(pairs) for pairs in ALL_KIND_PAIRS)


def test_every_case_is_parametrised_into_exactly_one_runner() -> None:
    """No case may be silently absent from the run: the five kind lists must partition
    ``FILES`` exactly — no gaps, no case counted twice.

    Asserted structurally rather than by reading ``_RECORDER`` from another test. A
    ``len(_RECORDER.executed) == len(CASES)`` assertion would depend on the
    parametrised runners having already executed, which makes it order-dependent and —
    worse — spuriously red under any filtered run (``pytest -k``, ``-x`` after an
    earlier failure, ``-n`` sharding). A test that fails when you select a single case
    trains people to ignore it. This one is a pure function of ``CASES`` and holds under
    any invocation, and it catches the two failures that actually happen when someone
    edits this file: a case the index lists that no runner claims, and a kind added to
    ``IMPLEMENTED_KINDS`` without a runner.

    **Residual gap, recorded rather than solved:** neither this nor a recorder-based
    check catches a ``pytest.mark.skip`` or an early ``return`` added to a runner *body*
    later. Only a session-scoped hook comparing collected-to-executed would, and that is
    a ``conftest.py`` change affecting every Python corpus runner in the repository.
    """
    routed = list(chain.from_iterable(ALL_KIND_PAIRS))
    routed_files = [f for f, _ in routed]
    assert sorted(routed_files) == sorted(FILES)
    assert len(routed_files) == len(set(routed_files))


def test_both_outcomes_are_exercised_in_each_implemented_kind() -> None:
    # A kind whose cases all expect the same thing would pin no distinction at all.
    for pairs in ALL_KIND_PAIRS:
        assert len({_outcome(c) for _, c in pairs}) >= 2


def test_every_section_ten_token_is_asserted_by_a_verify_case() -> None:
    # §10's set is closed at ten and §8 reaches every one of them. A token no verify
    # case asserts is a step whose ORDER is unpinned — the one class of divergence this
    # document exists to prevent, since every candidate ordering verifies the same valid
    # signatures and differs only in which token an invalid manifest reports.
    asserted = {_reason(c) for _, c in VERIFY_PAIRS if _reason(c) is not None}
    assert asserted == set(SIGNATURE_REASONS)


def test_skipped_cases_are_exactly_the_declared_deferrals() -> None:
    """The runner and ``conformance-coverage.json`` must not disagree.

    Without this, adding a case is silent in BOTH directions: the runner would not run
    it and the reconciler would not expect it, and the corpus would report a coverage it
    does not have. The declaration is read rather than restated here — a hard-coded list
    would make this test agree with itself and nothing else.

    ``.get`` with an empty default, because the expected answer is now *no* entry at
    all: a binding that defers nothing should not have to carry an empty array to say
    so, and a ``KeyError`` here would be this test failing for the wrong reason.
    """
    manifest = json.loads(_COVERAGE.read_text(encoding="utf-8"))
    deferred = manifest["languages"]["python"]["deferred"]
    declared = set(deferred.get("manifest-signature", []))
    # `FILES` is the index's own `file` list — `load_corpus` returns case BODIES and
    # discards that member, so the identities come from `corpus_files` rather than from
    # a second source of truth for the same list.
    assert set(FILES) - executed_case_files() == declared
    assert declared == set(), "this binding defers nothing in this corpus"


# ------------------------------------------------------------------------------ §4


@pytest.mark.parametrize(("file", "case"), BASE64URL_PAIRS, ids=_ids)
def test_base64url_cases(file: str, case: dict[str, object]) -> None:
    mode = case["mode"]
    text = str(case["input"])
    reason = _reason(case)

    if mode == "encode":
        assert reason is None, "an encoder cannot refuse, yet the case expects a token"
        assert base64url_encode(bytes.fromhex(text)) == _ok(case)
        _RECORDER.record(file)
        return

    if reason is not None:
        with pytest.raises(SignatureError) as excinfo:
            base64url_decode(text)
        assert excinfo.value.reason == reason
    else:
        assert base64url_decode(text).hex() == _ok(case)
    _RECORDER.record(file)


# ------------------------------------------------------------------------------ §5


@pytest.mark.parametrize(("file", "case"), THUMBPRINT_PAIRS, ids=_ids)
def test_thumbprint_cases(file: str, case: dict[str, object]) -> None:
    key = case["jwk"]
    reason = _reason(case)

    if reason is not None:
        with pytest.raises(SignatureError) as excinfo:
            jwk_thumbprint(key)  # type: ignore[arg-type]
        assert excinfo.value.reason == reason
        _RECORDER.record(file)
        return

    assert jwk_thumbprint(key) == _ok(case)  # type: ignore[arg-type]

    # Where the case pins §5 step 2's octets, assert them too: a binding can reach the
    # right digest by the wrong serialization only if the hash input is never asserted.
    expect = case["expect"]
    assert isinstance(expect, dict)
    canonical = expect.get("canonical")
    if canonical is not None:
        assert isinstance(key, dict)
        projection = {member: key[member] for member in ("crv", "kty", "x")}
        assert canonicalize(projection).encode("utf-8").hex() == canonical
    _RECORDER.record(file)


# ------------------------------------------------------------------------------ §7


@pytest.mark.parametrize(("file", "case"), ED25519_PAIRS, ids=_ids)
def test_ed25519_cases(file: str, case: dict[str, object]) -> None:
    """§7's primitive, exercised through the PRIVATE implementation.

    Nothing under ``nimbus_sdk.signing`` exports a raw verify and nothing should — see
    that package's docstring — so this reaches into ``_ed25519`` deliberately. The other
    two bindings point this kind at their runtime (WebCrypto, ``crypto/ed25519``); here
    the runtime *is* this module, which is exactly why these twelve cases matter more
    in Python than anywhere else.

    The kind never refuses: both booleans are outcomes, and a rejected encoding is a
    ``False`` rather than an exception — :func:`_ed25519.verify` never raises.
    """
    expected = _ok(case)
    assert isinstance(expected, bool), "an ed25519 case must expect a boolean"
    public_key = bytes.fromhex(str(case["publicKey"]))
    message = bytes.fromhex(str(case["message"]))
    signature = bytes.fromhex(str(case["signature"]))

    assert _ed25519.verify(public_key, message, signature) is expected
    _RECORDER.record(file)


# ------------------------------------------------------------------------------ §8


@pytest.mark.parametrize(("file", "case"), VERIFY_PAIRS, ids=_ids)
def test_verify_cases(file: str, case: dict[str, object]) -> None:
    """§8's ten ordered steps, and the four ordering resolutions §8 makes normative.

    These cases are the only thing in this binding that holds the step order: a
    verifier that checks ``alg`` before resolving ``kid``, or parses ``protected``
    before decoding ``signature``, accepts and rejects exactly the same manifests and
    differs only in the token it reports. Every such reordering is caught here and
    nowhere else.
    """
    manifest = case["manifest"]
    trusted = case["trustedKeys"]
    assert isinstance(trusted, list), "a verify case must carry a trustedKeys array"
    reason = _reason(case)

    if reason is None:
        # Returns None on success; anything raised is the failure.
        verify_manifest_signature(manifest, trusted)  # type: ignore[arg-type]
        _RECORDER.record(file)
        return

    with pytest.raises(SignatureError) as excinfo:
        verify_manifest_signature(manifest, trusted)  # type: ignore[arg-type]
    assert excinfo.value.reason == reason
    # §10 keeps canonical-json.md §9's set ALONGSIDE the token rather than absorbing it,
    # so where a case pins the underlying reason, assert the field it travels in.
    canonicalization = _canonicalization_reason(case)
    if canonicalization is not None:
        assert excinfo.value.canonicalization_reason == canonicalization
    _RECORDER.record(file)


# ------------------------------------------------------------------------------ §9


@pytest.mark.parametrize(("file", "case"), SIGN_PAIRS, ids=_ids)
def test_sign_cases(file: str, case: dict[str, object]) -> None:
    """§9's signer, asserted on the envelope's exact octets.

    Both members are compared, not just the signature: ``protected`` carries the ``kid``
    §9 step 2 derives, so a signer that thumbprints the private JWK without §5's
    projection produces a valid signature over the wrong header and would pass a
    signature-only assertion.
    """
    manifest = case["manifest"]
    private_key = case["privateKey"]
    reason = _reason(case)

    if reason is not None:
        with pytest.raises(SignatureError) as excinfo:
            sign_manifest(manifest, private_key)  # type: ignore[arg-type]
        assert excinfo.value.reason == reason
        _RECORDER.record(file)
        return

    envelope = sign_manifest(manifest, private_key)  # type: ignore[arg-type]
    expected = _ok(case)
    assert isinstance(expected, dict), "a sign case must expect an envelope object"
    assert envelope["protected"] == expected["protected"]
    assert envelope["signature"] == expected["signature"]
    _RECORDER.record(file)
