"""Drive canonicalization from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases.
"""

from __future__ import annotations

import pytest
from _conformance_report import corpus_files, recorder

from nimbus_sdk import load_corpus
from nimbus_sdk.signing import (
    CanonicalizationError,
    canonicalize,
    canonicalize_manifest,
)

CASES = load_corpus("canonical-json")
FILES = corpus_files("canonical-json")
assert len(FILES) == len(CASES), "the index and load_corpus disagree on the case count"
_RECORDER = recorder("canonical-json")


def _ids() -> list[str]:
    return [str(case["description"]) for case in CASES]


def test_the_corpus_is_not_empty() -> None:
    # A load_corpus that silently returned [] would make every parametrised test
    # below vanish rather than fail. A floor, not an exact pin: the TypeScript guard
    # holds the exact list, and duplicating it here would make every new case a
    # four-file edit.
    assert len(CASES) >= 21


def test_both_outcomes_are_exercised() -> None:
    outcomes = set()
    for case in CASES:
        expect = case["expect"]
        assert isinstance(expect, dict)
        outcomes.add(bool(expect["ok"]))
    assert outcomes == {True, False}


@pytest.mark.parametrize(
    ("file", "case"), list(zip(FILES, CASES, strict=True)), ids=_ids()
)
def test_case(file: str, case: dict[str, object]) -> None:
    mode = case["mode"]
    value = case["input"]
    expect = case["expect"]
    assert isinstance(expect, dict)

    def run() -> bytes:
        if mode == "manifest":
            assert isinstance(value, dict)
            return canonicalize_manifest(value)
        return canonicalize(value).encode("utf-8")

    if expect["ok"]:
        assert run().hex() == expect["canonical"]
    else:
        with pytest.raises(CanonicalizationError) as excinfo:
            run()
        assert excinfo.value.reason == expect["reason"]
    _RECORDER.record(file)
