"""Drive the icalendar battery from the published conformance corpus.

Reads the spec data bundled at build time into ``src/nimbus_sdk/_data/spec``, which
``spec_root()`` prefers over the repository's ``docs/spec``. That copy is gitignored and
regenerated by the hatch build hook, so **adding a case to docs/spec is not enough
locally**: without ``python -m pip install -e .`` first, this suite runs the previous
snapshot and passes while executing none of the new cases. ``test_spec_snapshot.py``
catches that; if it is red, this file is testing the wrong bytes.

Two kinds. A ``parse`` case supplies a document and expects the events it yields; a
``build`` case supplies a ``BuildEventInput`` and an injected ``now`` and expects the
produced document byte for byte, which is what preamble §R5 requires of a builder.

The comparison converts the BINDING'S output into the corpus's shape rather than the
reverse, so a case with a mistyped key fails rather than silently matching, and it
compares the whole thirteen-member event at once rather than member by member -- a
per-member loop never looks at a member the corpus later grows.
"""

from __future__ import annotations

from typing import Any

import pytest
from _conformance_report import corpus_files, recorder

from nimbus_sdk import load_corpus
from nimbus_sdk.icalendar import (
    BuildEventInput,
    ParsedEvent,
    build_vevent,
    parse_icalendar,
)

CASES = load_corpus("icalendar")
FILES = corpus_files("icalendar")
assert len(FILES) == len(CASES), "the index and load_corpus disagree on the case count"
_RECORDER = recorder("icalendar")

KINDS = frozenset({"parse", "build"})

#: §1's thirteen members, spelled as the corpus spells them. The binding uses Python
#: casing (``recurrence_id``, ``all_day``); this maps back, and does NOT rename the
#: corpus, which is language-neutral.
MEMBERS: tuple[tuple[str, str], ...] = (
    ("uid", "uid"),
    ("recurrenceId", "recurrence_id"),
    ("summary", "summary"),
    ("description", "description"),
    ("location", "location"),
    ("start", "start"),
    ("end", "end"),
    ("allDay", "all_day"),
    ("status", "status"),
    ("organizer", "organizer"),
    ("attendees", "attendees"),
    ("rrule", "rrule"),
    ("dtstamp", "dtstamp"),
)


def _ids() -> list[str]:
    return [str(case["description"]) for case in CASES]


def _comparable(event: ParsedEvent) -> dict[str, object]:
    """The binding's event in the corpus's shape, all thirteen members."""
    out: dict[str, object] = {}
    for wire, attr in MEMBERS:
        value = getattr(event, attr)
        out[wire] = list(value) if wire == "attendees" else value
    return out


def test_the_corpus_is_not_empty() -> None:
    # A load_corpus that silently returned [] would make every parametrised test below
    # vanish rather than fail. A floor, not an exact count: the TypeScript guard holds
    # the exact list, and duplicating it here would detect nothing.
    assert len(CASES) >= 50


def test_every_kind_is_exercised() -> None:
    assert {str(case["kind"]) for case in CASES} == KINDS


def test_both_parse_outcomes_are_exercised() -> None:
    counts = [
        len(case["expect"]["events"])  # type: ignore[index]
        for case in CASES
        if case["kind"] == "parse"
    ]
    assert any(n > 0 for n in counts), "no parse case yields an event"
    assert any(n == 0 for n in counts), "no parse case yields an empty list"


def test_an_empty_value_is_distinguished_from_an_absence() -> None:
    # §1 makes the empty string a reachable answer, distinct from a property that was
    # not present. Without a case for both, a binding collapsing them passes -- which is
    # exactly what Go's zero-value convention would do. Asserted here too, because the
    # Python and Go runners never see the case schema.
    seen: set[tuple[str, object]] = set()
    for case in CASES:
        if case["kind"] != "parse":
            continue
        for event in case["expect"]["events"]:  # type: ignore[index]
            for member in ("summary", "organizer"):
                seen.add((member, event[member]))
    for member in ("summary", "organizer"):
        assert (member, "") in seen, f"no case pins an empty {member}"
        assert (member, None) in seen, f"no case pins an absent {member}"


def test_the_u_0130_fold_is_pinned() -> None:
    # U+0130 is the one code point whose Python lowercase is longer than itself, so a
    # binding using str.lower() to find an index into the original is off by one from it
    # onward. Without a case carrying it, that wrong implementation passes.
    carrying = [case for case in CASES if "İ" in str(case.get("ics", ""))]
    assert carrying, "no case contains U+0130, so §5.3's ASCII fold is unpinned"


def test_the_whitespace_set_is_pinned_in_both_directions() -> None:
    # U+FEFF is IN §R7's set and str.strip() does not remove it; U+001C is OUT of the
    # set and str.strip() does. One case each, failing in opposite directions.
    texts = [str(case.get("ics", "")) for case in CASES if case["kind"] == "parse"]
    assert any("﻿" in t for t in texts), "no case pins U+FEFF as trimmed"
    assert any("" in t for t in texts), "no case pins U+001C as kept"


def test_no_build_case_expects_a_fold() -> None:
    # §7, settled by RFC-0018: a line of any length is emitted whole. At least two cases
    # must exceed 75 octets, or the rule asserts nothing.
    long_cases = 0
    for case in CASES:
        if case["kind"] != "build":
            continue
        ics = case["expect"]["ics"]  # type: ignore[index]
        assert isinstance(ics, str)
        assert "\r\n " not in ics, "a build case expects a CRLF+SPACE fold"
        assert "\r\n\t" not in ics, "a build case expects a CRLF+HTAB fold"
        if len(ics.encode("utf-8")) > 75:
            long_cases += 1
    assert long_cases >= 2, "no build case exceeds 75 octets, so §7 asserts nothing"


@pytest.mark.parametrize(
    ("file", "case"), list(zip(FILES, CASES, strict=True)), ids=_ids()
)
def test_case(file: str, case: dict[str, object]) -> None:
    expect = case["expect"]
    assert isinstance(expect, dict)
    kind = case["kind"]

    if kind == "build":
        # Type-asserted rather than defaulted: a mistyped key would otherwise run the
        # builder against None and fail for the wrong reason.
        raw: Any = case["input"]
        now: Any = case["now"]
        assert isinstance(raw, dict), f"{file}: no input"
        assert isinstance(now, str), f"{file}: no now"
        attendees = raw.get("attendees")
        event = BuildEventInput(
            uid=raw["uid"],
            summary=raw["summary"],
            start=raw["start"],
            end=raw["end"],
            description=raw.get("description"),
            location=raw.get("location"),
            attendees=None if attendees is None else tuple(attendees),
        )
        assert build_vevent(event, now) == expect["ics"], f"{file}"
        _RECORDER.record(file)
        return

    ics: Any = case["ics"]
    assert isinstance(ics, str), f"{file}: no ics"
    actual = [_comparable(event) for event in parse_icalendar(ics)]
    assert actual == expect["events"], f"{file}"
    _RECORDER.record(file)
